name: Release Package

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
      - run: cargo build --release
      - uses: softprops/action-gh-release@v2
        with:
          files: ./target/release/exeter